### ISSUE TITLE
Problems Compiling on Mac OS X (Apple Mach-O Linker (Id) Error)

### ISSUE THREAD

**Issue by ranveeraggarwal** [gameoverhack/ofxOpenNI#54]
I followed the precise instructions to get the example code working on OS X, but whenever I build (it compiles), (and on linking) I get the following error:

```
ld: library not found for -lXnFormats
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Basically the linker cannot find `-lXnFormats`.
What can be done to solve this error?

PS: I am using XCode 7.1 with OS X El Capitan v10.11.1.

**Comment by ccerhan** [comment]
Hello,

Yo can find my answer in [this](http://stackoverflow.com/questions/33681299/apple-mach-o-linker-id-error-for-openframeworks/34559001#34559001) link.

I hope it works for you, too.

**Comment by ranveeraggarwal** [comment]
Yes, this worked. Thanks :smile:
