### ISSUE TITLE
problem to execute ofxOpenNI with osx 10.6.8 and 10.7.2 

### ISSUE THREAD

**Issue by viniciolindo** [gameoverhack/ofxOpenNI#9]
i have this error in execution:
dyld: Library not loaded: /opt/local/lib/libusb-1.0.0.dylib
  Referenced from: /Users/viniciolindo/Documents/of_preRelease_v007_osx/apps/myApps/openNI-demoAllFeatures/bin/openNISample007Debug.app/Contents/MacOS/./../../../data/openni/lib/libOpenNI.dylib
  Reason: image not found

it's strange because libusb is in correct folder that is: myAppsFolder/example/bin/data/openni/lib/

**Comment by gameoverhack** [comment]
Yep seems to affect some users and not others - i think maybe in this release I did not correctly author the libusb dyld...

Try executing change_exec_paths.sh using terminal (ie., cd myAppsFolder/example/bin/data/openni/lib/ and then sudo ./change_exec_paths.sh )...

**Comment by jvcleave** [comment]
One thing I noticed with this version is this message

Reason: Incompatible library version: libOpenNI.dylib requires version 2.0.0 or later, but libusb-1.0.0.dylib provides version 1.0.0

Quick fix is to `sudo port install libusb-devel +universal` (with MacPorts) but that version doesn't seem compatible with libusb-compat which other libraries use

**Comment by tucano** [comment]
Quick FIX:

install_name_tool -change "/opt/local/lib/libusb-1.0.0.dylib" "@executable_path/./../../../data/openni/lib/libusb-1.0.0.dylib" libOpenNI.dylib

otool -L libOpenNI.dylib

libOpenNI.dylib:
@executable_path/./../../../data/openni/lib/libOpenNI.dylib (compatibility version 0.0.0, current version 0.0.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 550.44.0)
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
@executable_path/./../../../data/openni/lib/libusb-1.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.11)
/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.9.0)

CFR: issue #18 (sorry for the duplication)
